// import type { StoreData, Order, Product, Customer, Coupon } from "./types";

// export const mockStore: StoreData = {
//   id: "abc12345-def6-7890",
//   admin_name: "محمد العمري",
//   admin_email: "mohammed@example.com",
//   store_name: "متجر النخبة",
//   slug: "elite-store",
//   location: "الرياض، المملكة العربية السعودية",
//   phone: "+966 50 000 0000",
//   store_type: "fashion",
//   created_at: "2024-03-15T10:00:00Z",
//   is_active: true,
// };

// export const mockOrders: Order[] = [
//   {
//     id: "#10045",
//     customer: "سارة الأحمد",
//     amount: 485,
//     status: "completed",
//     date: "2025-01-10",
//     items: 3,
//   },
//   {
//     id: "#10044",
//     customer: "خالد المنصور",
//     amount: 1200,
//     status: "processing",
//     date: "2025-01-10",
//     items: 5,
//   },
//   {
//     id: "#10043",
//     customer: "نورة السعيد",
//     amount: 320,
//     status: "pending",
//     date: "2025-01-09",
//     items: 2,
//   },
//   {
//     id: "#10042",
//     customer: "عبدالله الزهراني",
//     amount: 750,
//     status: "completed",
//     date: "2025-01-09",
//     items: 4,
//   },
//   {
//     id: "#10041",
//     customer: "فاطمة العتيبي",
//     amount: 190,
//     status: "cancelled",
//     date: "2025-01-08",
//     items: 1,
//   },
//   {
//     id: "#10040",
//     customer: "يوسف الحربي",
//     amount: 2100,
//     status: "completed",
//     date: "2025-01-08",
//     items: 7,
//   },
//   {
//     id: "#10039",
//     customer: "ريم الشمري",
//     amount: 560,
//     status: "processing",
//     date: "2025-01-07",
//     items: 3,
//   },
//   {
//     id: "#10038",
//     customer: "أحمد القحطاني",
//     amount: 890,
//     status: "completed",
//     date: "2025-01-07",
//     items: 4,
//   },
// ];

// export const mockCustomers: Customer[] = [
//   {
//     id: "c1",
//     name: "سارة الأحمد",
//     email: "sara@example.com",
//     orders: 12,
//     totalSpent: 5840,
//     joinDate: "2024-06-01",
//     status: "active",
//   },
//   {
//     id: "c2",
//     name: "خالد المنصور",
//     email: "khalid@example.com",
//     orders: 8,
//     totalSpent: 9600,
//     joinDate: "2024-07-15",
//     status: "active",
//   },
//   {
//     id: "c3",
//     name: "نورة السعيد",
//     email: "noura@example.com",
//     orders: 5,
//     totalSpent: 1600,
//     joinDate: "2024-08-20",
//     status: "active",
//   },
//   {
//     id: "c4",
//     name: "عبدالله الزهراني",
//     email: "abdullah@example.com",
//     orders: 3,
//     totalSpent: 2250,
//     joinDate: "2024-09-10",
//     status: "inactive",
//   },
//   {
//     id: "c5",
//     name: "فاطمة العتيبي",
//     email: "fatima@example.com",
//     orders: 7,
//     totalSpent: 1330,
//     joinDate: "2024-10-01",
//     status: "active",
//   },
//   {
//     id: "c6",
//     name: "يوسف الحربي",
//     email: "yousuf@example.com",
//     orders: 15,
//     totalSpent: 31500,
//     joinDate: "2024-05-15",
//     status: "active",
//   },
// ];

// export const mockCoupons: Coupon[] = [
//   {
//     id: "cp1",
//     code: "WELCOME20",
//     discount: 20,
//     type: "percentage",
//     uses: 45,
//     maxUses: 100,
//     expiry: "2025-03-31",
//     active: true,
//   },
//   {
//     id: "cp2",
//     code: "SAVE50",
//     discount: 50,
//     type: "fixed",
//     uses: 12,
//     maxUses: 50,
//     expiry: "2025-02-28",
//     active: true,
//   },
//   {
//     id: "cp3",
//     code: "VIP15",
//     discount: 15,
//     type: "percentage",
//     uses: 89,
//     maxUses: 200,
//     expiry: "2025-06-30",
//     active: true,
//   },
//   {
//     id: "cp4",
//     code: "SUMMER30",
//     discount: 30,
//     type: "percentage",
//     uses: 200,
//     maxUses: 200,
//     expiry: "2024-09-30",
//     active: false,
//   },
// ];

export const chartData = [
  { month: "يوليو", monthEn: "Jul", sales: 4200, orders: 38, visits: 1200 },
  { month: "أغسطس", monthEn: "Aug", sales: 5800, orders: 52, visits: 1450 },
  { month: "سبتمبر", monthEn: "Sep", sales: 3900, orders: 35, visits: 980 },
  { month: "أكتوبر", monthEn: "Oct", sales: 7200, orders: 64, visits: 1800 },
  { month: "نوفمبر", monthEn: "Nov", sales: 9500, orders: 86, visits: 2400 },
  { month: "ديسمبر", monthEn: "Dec", sales: 12400, orders: 110, visits: 3100 },
  { month: "يناير", monthEn: "Jan", sales: 8600, orders: 78, visits: 2100 },
];

 export const STORE_TYPE_LABELS: Record<string, { ar: string; en: string }> = {
   fashion: { ar: "👗 أزياء وملابس", en: "👗 Fashion & Clothing" },
   electronics: { ar: "📱 إلكترونيات", en: "📱 Electronics" },
   food: { ar: "🍔 طعام ومشروبات", en: "🍔 Food & Beverages" },
   beauty: { ar: "💄 جمال وتجميل", en: "💄 Beauty & Cosmetics" },
   home: { ar: "🏠 منزل وأثاث", en: "🏠 Home & Furniture" },
   sports: { ar: "⚽ رياضة", en: "⚽ Sports & Outdoors" },
   books: { ar: "📚 كتب وتعليم", en: "📚 Books & Education" },
   jewelry: { ar: "💍 مجوهرات", en: "💍 Jewelry & Accessories" },
   toys: { ar: "🧸 ألعاب", en: "🧸 Toys & Games" },
   other: { ar: "🏪 أخرى", en: "🏪 Other" },
 };
